# Generated by Django 4.2.7 on 2025-12-12 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('mercado', models.CharField(choices=[('acciones', 'Acciones'), ('cfi', 'CFI'), ('fondos_mutuos', 'Fondos Mutuos')], max_length=30)),
                ('ano', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('factor_actualizado', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('instrumento', models.CharField(blank=True, max_length=20, null=True)),
                ('secuencia_evento', models.IntegerField(default=10001)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('sistema', 'Sistema')], default='manual', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calificacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id_factor', models.AutoField(db_column='ID_factor', primary_key=True, serialize=False)),
                ('nombre_factor', models.CharField(max_length=50)),
                ('valor_factor', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'factor',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(db_column='ID_permiso', primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id_usuario_permiso', models.AutoField(db_column='ID_usuario_permiso', primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('fk_id_permiso', models.ForeignKey(db_column='FK_ID_permiso', on_delete=django.db.models.deletion.PROTECT, to='NuamApp.permiso')),
                ('fk_id_usuario', models.ForeignKey(db_column='FK_ID_usuario', on_delete=django.db.models.deletion.CASCADE, to='NuamApp.usuario')),
            ],
            options={
                'db_table': 'usuario_permiso',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='ID_reporte', primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=30)),
                ('fecha_generacion', models.DateField()),
                ('archivo_url', models.CharField(blank=True, max_length=150, null=True)),
                ('fk_id_usuario', models.ForeignKey(db_column='FK_ID_usuario', on_delete=django.db.models.deletion.CASCADE, to='NuamApp.usuario')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id_corredor', models.AutoField(db_column='ID_corredor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('fk_usuario', models.ForeignKey(db_column='FK_usuario_ID', on_delete=django.db.models.deletion.CASCADE, to='NuamApp.usuario')),
            ],
            options={
                'db_table': 'corredor',
            },
        ),
        migrations.CreateModel(
            name='CalificacionFactor',
            fields=[
                ('id_calificacion_factor', models.AutoField(db_column='ID_calificacion_factor', primary_key=True, serialize=False)),
                ('fk_id_calificacion', models.ForeignKey(db_column='FK_ID_calificacion', on_delete=django.db.models.deletion.CASCADE, to='NuamApp.calificacion')),
                ('fk_id_factor', models.ForeignKey(db_column='FK_ID_factor', on_delete=django.db.models.deletion.PROTECT, to='NuamApp.factor')),
            ],
            options={
                'db_table': 'calificacion_factor',
            },
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fk_id_corredor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NuamApp.corredor'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=500)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NuamApp.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='Archivocarga',
            fields=[
                ('id_archivo', models.AutoField(db_column='ID_archivo', primary_key=True, serialize=False)),
                ('tipo_archivo', models.CharField(max_length=30)),
                ('fecha_carga', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('archivo_url', models.CharField(blank=True, max_length=150, null=True)),
                ('fk_id_usuario', models.ForeignKey(db_column='FK_ID_usuario', on_delete=django.db.models.deletion.CASCADE, to='NuamApp.usuario')),
            ],
            options={
                'db_table': 'archivocarga',
            },
        ),
    ]
