# Generated by Django 4.2.7 on 2025-12-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NuamApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='detalles',
        ),
    ]
